### ISSUE TITLE
此error 如何解决，不会python

### ISSUE THREAD

**Issue by hcliu987** [limkokhole/duboku-downloader#1]
![image](https://user-images.githubusercontent.com/52879991/80226415-eab5b680-867e-11ea-829e-2c537fe2dc4c.png)
![1587740205811](https://user-images.githubusercontent.com/52879991/80226433-f1442e00-867e-11ea-85c9-93bead7fea54.jpg)
ru h如何解决

**Comment by limkokhole** [comment]
如果你的平台是 Windows，你必须下载 win_64_source 整个目录(里头包含了 crypto_py_aes.py)， 然后在目录里面运行 duboku_console.py， 并非只下载 duboku_console.py 一个文件。

**Comment by yyy1229** [comment]
mac error ModuleNotFoundError: No module named 'calmjs'
谢谢

**Comment by limkokhole** [comment]
> mac error ModuleNotFoundError: No module named 'calmjs'
> 谢谢

`python3 -m pip install calmjs` 或主要的命令行界面依赖 `python3 -m pip install -r requirements_py3_console.txt` 或图形界面依赖 `python3 -m pip install -r requirements_py3_gui.txt`

**Comment by yyy1229** [comment]
thanks! got it
