### ISSUE TITLE
显示已完成，但下载目录没有文件

### ISSUE THREAD

**Issue by Orokapei** [limkokhole/duboku-downloader#3]
如图，下载进度是秒完成的= =，没有详细日志，也找不到问题
![image](https://user-images.githubusercontent.com/23261300/83423403-7fb98580-a45d-11ea-8226-8273759fbdbb.png)

**Comment by Orokapei** [comment]
url是https://www.duboku.net/voddetail/1382.html
底下的尝试url也是能打开的（

**Comment by limkokhole** [comment]
我试了没问题：
![1591087419_2020-06-02_O7gN8XTTTL](https://user-images.githubusercontent.com/4859895/83509000-53eddc80-a4fd-11ea-9c36-782bda097e92.png)

如果你仍然不能下载，我新增了 --debug (或 -g) 选项，你可以用该选项储存的 duboku_epN.log 文件，以附件形式上传上来。

**Comment by Orokapei** [comment]
非常感谢，但是还是不行= =下面是ep17的日志
[duboku_ep17.log](https://github.com/limkokhole/duboku-downloader/files/4716616/duboku_ep17.log)

**Comment by Orokapei** [comment]
> 我试了没问题：
> ![1591087419_2020-06-02_O7gN8XTTTL](https://user-images.githubusercontent.com/4859895/83509000-53eddc80-a4fd-11ea-9c36-782bda097e92.png)
> 
> 如果你仍然不能下载，我新增了 --debug (或 -g) 选项，你可以用该选项储存的 duboku_epN.log 文件，以附件形式上传上来。

= =以README.md中的示例python3 duboku_console.py https://www.duboku.net/voddetail/1152.html -f 返校 --debug 也是一样的结果
[duboku_ep1.log](https://github.com/limkokhole/duboku-downloader/files/4716631/duboku_ep1.log)

**Comment by limkokhole** [comment]
我检查了你的 html 并没有问题， 所以我估计是 calmjs 版本问题。

请执行该命令， 然后把日志 calmjs.log 上传到这:

`python3 -m pip show calmjs > calmjs.log; python3 -m trace --trace --ignore-dir ~/.local/lib/ --ignore-dir /usr/lib/ --ignore-dir /usr/local/lib/ duboku_console.py https://www.duboku.net/voddetail-1152.html -f 返校 >> calmjs.log`

**Comment by Orokapei** [comment]
> 我检查了你的 html 并没有问题， 所以我估计是 calmjs 版本问题。
> 
> 请执行该命令， 然后把日志 calmjs.log 上传到这:
> 
> `python3 -m pip show calmjs > calmjs.log; python3 -m trace --trace --ignore-dir ~/.local/lib/ --ignore-dir /usr/lib/ --ignore-dir /usr/local/lib/ duboku_console.py https://www.duboku.net/voddetail-1152.html -f 返校 >> calmjs.log`

= =
[calmjs.log](https://github.com/limkokhole/duboku-downloader/files/4717264/calmjs.log)

**Comment by limkokhole** [comment]
python3 用户必须先执行命令 `python3 -m pip install beautifulsoup4==4.7.1` 才能正常使用。因为[BeautifulSoup 最新版本 4.9.1](https://pypi.org/project/beautifulsoup4/) 不再考虑兼容 python 2。完整需求请参考 r[equirements_py3_console.txt](https://github.com/limkokhole/duboku-downloader/blob/master/linux_source/requirements_py3_console.txt) 文件。

**顺便提醒: Linux 用户请确保已安装了 ffmpeg。**

![1591312703_2020-06-05_gG6FZIzkku](https://user-images.githubusercontent.com/4859895/83819625-f0320200-a6fc-11ea-98de-72b30ffe42f8.png)

**Comment by Orokapei** [comment]
> beautifulsoup4

非常感谢，就是beautifulsoup版本的问题，现在已经好了，感谢大佬QAQ
