### ISSUE TITLE
Invalid data found when processing input

### ISSUE THREAD

**Issue by AlluringPixel** [limkokhole/duboku-downloader#5]
ffmpeg version N-98112-g7aa7d68971-ffmpeg-windows-build-helpers Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8.3.0 (GCC)
  configuration: --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/xiaobai/Downloads/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --disable-everything --disable-network --disable-autodetect --disable-doc --disable-ffprobe --disable-swscale --disable-avdevice --disable-swresample --disable-bzlib --disable-sndio --disable-sdl2 --disable-libxcb_xfixes --disable-libxcb --disable-libxcb_shape --disable-libxcb_shm --disable-lzma --disable-iconv --disable-xlib --disable-zlib --enable-bsf='extract_extradata,aac_adtstoasc' --enable-muxer='mp4,mpegts' --enable-demuxer='mpegts,aac,h264' --enable-decoder='aac,h264' --enable-parser='h264,aac' --enable-protocol=file --enable-libsvthevc --enable-libaom --enable-libvpx --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-filter=frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxvid --enable-libxavs --enable-static --disable-shared --prefix=/home/xiaobai/Downloads/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32
  libavutil      56. 53.100 / 56. 53.100
  libavcodec     58. 92.100 / 58. 92.100
  libavformat    58. 46.101 / 58. 46.101
  libavfilter     7. 86.100 /  7. 86.100
  libpostproc    55.  8.100 / 55.  8.100
[AVIOContext @ 000001cc48fe82c0] Statistics: 3056 bytes read, 0 seeks
9a4de9f1-69e1-4672-a04f-7ef7284dc950.ts_1598976721.5740125.temp: Invalid data found when processing input

**Comment by limkokhole** [comment]
请提供相关链接和第几集出现上述错误。谢谢。

**Comment by AlluringPixel** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/63203649/91886887-2e1ad400-ecb4-11ea-9c72-9f325c09edf8.png)

链接和剧集
python duboku_console.py https://www.duboku.co/vodplay/1554-1-38.html -d I:Liuli --from-ep 38 -to-ep 38
我使用Windows 10操作系统
对不起，我的语言不好

**Comment by limkokhole** [comment]
我没遇到该问题。或许是网络问题导致下载不完整，请尝试再下载。

如果还是不行，请点击下载 [https://v.wedubo.com/20200901/69OYAim7/hls/JOC0UX7T.ts](https://v.wedubo.com/20200901/69OYAim7/hls/JOC0UX7T.ts) ， 然后上传给我检查。

如果你懂使用命令行 wget/curl 命令那就更好， ，能下载 [https://v.wedubo.com/20200901/69OYAim7/hls/JOC0UX7T.ts](https://v.wedubo.com/20200901/69OYAim7/hls/JOC0UX7T.ts) 然后上传更详细的日志给我。

**Comment by limkokhole** [comment]
已解决， 请 git pull。

Fixed with commit https://github.com/limkokhole/duboku-downloader/commit/3aaeeb5358b6df915baadeee833362137148f17f
